modLoader="kotlinforforge"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/shkschneider/mc_awesome/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/shkschneider/mc_awesome"
logoFile="assets/awesome/icon.png"
credits="ShkSchneider"
authors="ShkSchneider"
description='''
Modularized Vanilla++ mod for Minecraft.
Includes crystals, experience management, extras, commands, enchantments, and more.
'''

[[dependencies.awesome]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="kotlinforforge"
mandatory=true
versionRange="[4.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="architectury"
mandatory=true
versionRange="[8,)"
ordering="NONE"
side="BOTH"
