modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/shkschneider/mc_awesome/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/shkschneider/mc_awesome"
logoFile="assets/awesome/icon.png"
credits="ShkSchneider"
authors="ShkSchneider"
description='''
Modularized Vanilla++ mod for Minecraft.
Includes crystals, experience management, extras, commands, enchantments, and more.
'''

[[dependencies.awesome]]
modId="forge"
mandatory=true
versionRange="[50,)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="kotlinforforge"
mandatory=true
versionRange="[5.6.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.awesome]]
modId="architectury"
mandatory=true
versionRange="[12,)"
ordering="NONE"
side="BOTH"
